### ISSUE TITLE
Editing side on BasketConstituent reports success but does not apply new value

### ISSUE THREAD

**Issue by heswell** [finos/vuu#967] opened 2023-11-14 11:42 UTC
Within the basket trading feature, the constituents of an 'off market' basket offer a context menu option to set side. When the menu rpc message is submitted by client, it is acked by an EDIT_SUCCESS response from the server. Side is not actually updated on the selected row(s) though

**Comment by naleeha** [comment] 2023-11-21 10:12
Duplicate of https://github.com/finos/vuu/issues/982

**Closed by naleeha** 2023-11-21 10:12 UTC
